### ISSUE TITLE
クラス図作成

### ISSUE THREAD

**Issue by DenjiMk2** [MokuseiPoke/PokeTaimen#1]
発表の時にわかりやすい様にクラス図を作成したい。

**Comment by DenjiMk2** [comment]
2ef4db2b75eb53ad6c6ce85e52a7f4b603b3e4fd クラス図を二つに分けた。

lightClassの方はgetterやsetterなどを抜いて見やすく概念を説明するとき用のスケッチへ、いままでのmainClassは、全部のメソッドをAmasterUMLの機能で自動生成して、作業量を説明する時の図へ

**Comment by nes801** [comment]
eb18f1760b5bd2728546481f73c31865484dfd9b　完成。main文とGUI関連のクラス図を更新
